services:
  api_gatway:
    image: devopsfaith/krakend:2.9
    container_name: api_gatway_ct
    volumes:
      - ./krakend:/etc/krakend/
    depends_on:
      - diabetes_predictor_service
    ports:
      - "8080:8081"  
  diabetes_predictor_service:
    build:
      context: ./../../../lab6/exercises/modelservice
    container_name: diabetes_predictor_service_ct
    ports:
      - "5002:5000"