name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle-shop-bigquery-db'

model-paths: ["models"]
seed-paths: ["data"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
