services:
  api_gatway:
    image: devopsfaith/krakend:2.9
    container_name: api_gatway_ct
    volumes:
      - ./krakend:/etc/krakend/
    depends_on:
      - inventory_service
      - supplier_service
    ports:
      - "8080:8081"
  inventory_service:
    build:
      context: ./../../../lab6/inventoryservice
    container_name: inventory_service_ct
    ports:
      - "5000:5000"
  supplier_service:
    build:
      context: ./../../../lab6/exercises/supplierservice
    container_name: supplier_service_ct
    ports:
      - "5003:5000"