jaffle_shop_metrics-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth-secrets
      project: your_project_id
      dataset: jaffle_shop
      threads: 2
      token: your_access_token
